// <auto-generated />
using System;
using CounterPartyDomain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CounterPartyDomain.Migrations
{
    [DbContext(typeof(CountryPartyImporterDbContext))]
    partial class CountryPartyImporterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CounterPartyDomain.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("ChamberOfCommerce");

                    b.Property<string>("ChamberOfCommerceCi");

                    b.Property<int>("CompanyType");

                    b.Property<string>("CountryVAT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsCarrier");

                    b.Property<bool>("IsCustomClerance");

                    b.Property<bool>("IsExchangeBroker");

                    b.Property<bool>("IsForwarder");

                    b.Property<bool>("IsWareHouse");

                    b.Property<string>("LegalName")
                        .IsRequired();

                    b.Property<int?>("MailAddressId");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TradingName")
                        .IsRequired();

                    b.Property<bool>("Unused");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
